import Login from '../views/login/index';
import Dashboard from '../views/dashboard';
import Dispatch from '../views/dispatch';
import Reception from '../views/reception';
import Order from '../views/order';
import OrderInformation from '../views/orderInformation';
import ConfirmOrder from '../views/confirmOrder';
import Search from '../views/Search';
import OrderSignature from '../views/orderSignature';
export default {ConfirmOrder, Search, Dashboard, Dispatch, Login, Order, OrderSignature, OrderInformation, Reception};
